### ISSUE TITLE
Add task to rebuild logux.io on new release

### ISSUE THREAD

**Issue by ai** [logux/vuex#19]
You need to copy GitHub Actions from [Logux Redux](https://github.com/logux/redux/blob/master/.github/workflows/deploy.yml).

The only problem is that you need to generate a personal token at [Development page in Profile](https://github.com/settings/tokens) with `repo` scope.

Then you need to go to [Secrets settings of the repo](https://github.com/logux/redux/settings/secrets) and add ` DEPLOY_TOKEN` and ` DEPLOY_USER` tokens (your username).

After tokens creation you can commit GitHub Actions config to the repo. This config will send a command to `logux.io` repo and `deploy` task will catch the command by [this hook](https://github.com/logux/logux.io/blob/master/.github/workflows/deploy.yml#L7).

**Comment by euaaaio** [comment]
The only problem is that i don’t have permissions to settings 😝 
https://github.com/logux/vuex/settings — 404

**Comment by ai** [comment]
Permission granted :pilot:

**Comment by euaaaio** [comment]
Looks like deploy action failed: https://github.com/logux/vuex/runs/599640422?check_suite_focus=true

Maybe I need write permissions for logux/logux.io?

**Comment by ai** [comment]
I gave you write permission to `logux.io`. Can you change `on` to `push` in the workflow file and try to deploy logux.io again?

**Comment by euaaaio** [comment]
@ai, it works

**Comment by ai** [comment]
Great =^_^=
