### ISSUE TITLE
Simple examples

### ISSUE THREAD

**Issue by euaaaio** [logux/vuex#24]
I want to make some simple examples based on [vuex/examples](https://github.com/vuejs/vuex/tree/dev/examples).

1. Can I make PR to [logux/examples](https://github.com/logux/examples)?
2. What folder structure will we use?
3. Do we have any requirements for examples?

**Comment by ai** [comment]
My dream example:

1. ToDo and chat apps.
2. For each app, we have front-end and back-end examples.
3. For each front-end app, we have Redux, Vuex, pure JS examples.
4. For each back-end app, we have Node.js, Django, Rails examples.

```
examples/
  todo/
    frontend-redux/
    frontend-vuex/
    frontend-purejs/
    backend-node/
    backend-django/
    backend-rails/
  chat/
    frontend-redux/
    frontend-vuex/
    frontend-purejs/
    backend-node/
    backend-django/
    backend-rails/
```

**Comment by euaaaio** [comment]
Perfect dream 😼 

What about a simple counter example? Todo is a little hard for the beginners, I think. We often use counter as an example in the documentation, but it annoys me that I can't download it.

**Comment by ai** [comment]
I think counter example is too simple.

It is OK for the homepage, where we showing the system overview, but when user will go into examples, they will need more real applications.

**Comment by euaaaio** [comment]
Oh, I see what my problem is. Logux Vuex should have a guide about creating new client with Vue CLI. Like [Logux Redux’s New Client ](https://logux.io/guide/starting/new-client/).

**Comment by ai** [comment]
Yeap. If Vue CLI is the best way to start the project.

**Comment by vestild** [comment]
todo is simple enough - zero code shared between front and backend. but what if we want to share some? it's about backend-node of course.

**Comment by euaaaio** [comment]
What do you want to share?

**Comment by vestild** [comment]
any logic - event constructors (i think `.commit.sync(toggle(todo))` is better then `commit.sync({ type: 'toggle', id: todo.id, done: !todo.done })`) or reducers. in such simple examples it could or could not be useful

**Comment by euaaaio** [comment]
I think it's unnecessary. Parts should be independent so that developers can learn them in different language pairs. But let's ask @ai.

Also, from v3.1.0 we can use more familiar to Vue community API with string type:
```js
store.commit.sync('toggle', { id: todo.id, done: !todo.done }) 
```

**Comment by ai** [comment]
@euaaaio let’s close this issue, since we have an issue about the exampl in the main hub repository https://github.com/logux/logux/issues/5
