### ISSUE TITLE
commit.sync is not a function when using Vuex Modules

### ISSUE THREAD

**Issue by cosminv6u** [logux/vuex#31]
In Vuex MyModule it fails:
```
myAction({ commit }) {
    return commit.sync({type: MY_ACTION}); // this fails, commit.sync is not a function
}
```

Workaround:

Inside RootModule: add your mutation and call the mutation from your sub Module

```
mutations: {
        [MY_ACTION]: () => {
          this.store.commit('myModule/' + MY_ACTION)
    }
},
```

Inside MyModule, call the mutation from the Root Module, this will trigger Logux Sync

```
import Store from "../../store";

myAction({ commit }) {
    return Store.store.commit.sync({type: MY_ACTION});
}
```

ps: other things might be needed depending on your use case, the main idea is that you move things to the Root Module and delegate back to the ones in your sub Module, until this issue is fixed.

**Comment by euaaaio** [comment]
@cosminv6u I just published fix in v0.8.0-beta.1. Can you try to check it out?
```
npm i @logux/vuex@next
```

**Comment by cosminv6u** [comment]
Seems to work fine. I see the Action name is now composed of Namespace/MutationName.

**Comment by euaaaio** [comment]
> Seems to work fine. I see the Action name is now composed of Namespace/MutationName.

Logux improves every day. Thanks for your help.
I'll publish the release this weekends.
