### ISSUE TITLE
Add TS definitions

### ISSUE THREAD

**Issue by ai** [logux/vuex#4]
I recently converted all Logux project to TS support with `index.d.ts` files.

If you have no experience in TS, I can call my friend for help.

**Comment by mrdimidium** [comment]
Hi. Thank you for the work you do.

I can help with the first implementation of typings for the library.

Do Logux have any requirements or guidelines for typings? I noticed that other packages use [`check-dts`](https://github.com/ai/check-dts), and I think that it will also work perfectly here. Anything else?

**Comment by ai** [comment]
1. `check-dts`
2. If you have generics and type templates in public API you need to test them with `types.ts` and `errors.ts`
3. `any` and `object` should be used only in edge cases or semi-private API
4. TypeDoc for classes, public methods/properties, object’s properties.
