### ISSUE TITLE
Is it compatible with Pinia?

### ISSUE THREAD

**Issue by endlessuniverse** [logux/vuex#55]
Pinia is the default state management in Vue 3.
Thanks!

**Comment by endlessuniverse** [comment]
Nano Stores FTW!

**Comment by euaaaio** [comment]
I still support this package and even its version for Vue 2. Mostly thanks to the community. 

However, for the best performance and developer experience, I strongly recommend migrating to latest Logux Client. It does not depend on third-party state managers and is powered by Nano Stores, a type state manager specially designed for Logux.

Damn GitHub notifications. I don't know why I missed this issue. Sorry. I am always available on messengers like Discord, Telegram or via email to kick me.
